Add "transfer to unregistered emails" functionality
codex-protocol/deprecated.web.codex-viewer pull request #38
Opened 2018-10-26 21:27 UTC by Anaphase

This PR adds a `pendingUserCode` query parameter to the login page to support the new "transfer to unregistered emails" flow.

Also included are some minor frontend change that allow emails to be specified in place of an Ethereum address. @johnhforrest You'll probably wanna give these two files a look over and add any changes you were thinking of:

```
OAuth2AppTransferRecordForm.vue
ApproveTransferModal.vue
```

**IMPORTANT NOTE THAT I JUST THOUGHT OF**: we need to hide the email section in `ApproveTransferModal.vue` for non-simple users since savvy users shouldn't be able to send an email string in place of an address. That'll also probably affect the form validation too.

[See the corresponding back-end PR here.](https://github.com/codex-protocol/private-service.codex-registry-api/pull/25)

2018-10-29 14:43 UTC, johnhforrest commented
Going to review this one after we merge the login changes so this can take advantage of the feature flag there to hide the email field

2018-10-29 21:30 UTC, johnhforrest requested changes

2018-10-29 21:30 UTC, johnhforrest commented on src/components/modals/ApproveTransferModal.vue
> +      const input = [this.toEmailAddress || this.toEthAddress, this.codexRecord.tokenId]
This will break savvy users because it gets passed directly to the contract. They'll have to make an API call and use the Ethereum address in the response before signing the tx.

2018-10-29 21:30 UTC, johnhforrest commented on src/components/modals/ApproveTransferModal.vue
> +      if (this.toEmailAddress) {
If you add a link in the form to toggle between the 2 you can just validate that the one being shown is not empty

2018-10-29 21:30 UTC, johnhforrest commented on src/components/OAuth2AppTransferRecordForm.vue
> +      label="Receiving Ethereum or Email Address"
After you rebase against master you'll get the `config.supportEmailAccounts` flag to consume in this component. The label & placeholder text should change based on the value of this flag.

2018-10-29 21:30 UTC, johnhforrest commented on src/components/OAuth2AppTransferRecordForm.vue
> +      label="Receiving Ethereum or Email Address"
Oops, I realized this is the OAuth2 test app stuff. Same logic applies to the modal dialog though

2018-10-29 21:30 UTC, johnhforrest commented on src/components/modals/ApproveTransferModal.vue
> +      } else if (this.codexRecord.approvedAddress && this.toEthAddress === this.codexRecord.approvedAddress) {
Why is this extra check needed? We already know `this.toEthAddress` is truthy at this point

2018-10-29 21:30 UTC, johnhforrest commented on src/views/LoginView.vue
> +            @TODO: add a "claim with a different email?" link here when that
Would prefer to leave TODOs like this out for now because it's more of a feature request as opposed to an actionable item for cleanup

2018-10-29 21:30 UTC, johnhforrest commented on src/views/LoginView.vue
> +          // @TODO: should anything else happen here?
I think just swallow this error and show some generic text like `'Login to Codex Viewer to see what's waiting for you!'`

2018-10-29 21:30 UTC, johnhforrest commented on src/components/modals/ApproveTransferModal.vue
> +      const input = [this.toEmailAddress || this.toEthAddress, this.codexRecord.tokenId]
Oh I just realized you added this to the original description too. I'm fine w/ hiding it for savvy users--will be much easier if you add the toggle link to switch the form fields

2018-10-30 22:38 UTC, Anaphase commented on src/components/modals/ApproveTransferModal.vue
> +      } else if (this.codexRecord.approvedAddress && this.toEthAddress === this.codexRecord.approvedAddress) {
This isn't checking if `this.toEthAddress` is truthy, it's checking if it matches `this.codexRecord.approvedAddress`... I suppose checking if `this.codexRecord.approvedAddress` is truthy is redundant in a roundabout way, which I guess is what you meant here.

I suppose my reasoning was to make the condition explicit and "self contained" instead of relying on the reader to have read the previous conditions, i.e. this line is read as "if the record has already been approved and the to address matches the already-approved address."

2018-10-30 22:39 UTC, Anaphase commented on src/components/modals/ApproveTransferModal.vue
> +      } else if (this.codexRecord.approvedAddress && this.toEthAddress === this.codexRecord.approvedAddress) {
(That being said, I'll remove it)

2018-10-30 22:42 UTC, Anaphase commented on src/components/modals/ApproveTransferModal.vue
> +      } else if (this.codexRecord.approvedAddress && this.toEthAddress === this.codexRecord.approvedAddress) {
OH WAIT I know why it was in there. Originally I didn't have the separate email check above this, so this block once read:

```javascript
if (!this.toEthAddress && !this.toEmailAddress) {
  errors.push('Ethereum address or email address is required')
} else if (this.toEthAddress === this.user.address) {
  errors.push('You cannot transfer to yourself')
} else if (this.codexRecord.approvedAddress && this.toEthAddress === this.codexRecord.approvedAddress) {
  errors.push('This address has already been approved for transfer')
} else if (!this.instance.utils.isAddress(this.toEthAddress)) {
  errors.push('Invalid Ethereum address')
}
```

Notice the first line changed too, which required the condition in question to be updated as well (otherwise non-approved records would match a null `toEthAddress`). Then I broke the `this.toEmailAddress` check out into it's own block above and this was an unnecessary leftover.

2018-10-30 22:44 UTC, Anaphase commented on src/components/modals/ApproveTransferModal.vue
> +      if (this.toEmailAddress) {
Yeah that was just a little more work than I wanted to do at the time lol, I'll see if I can clean this up 👍🏻

2018-10-31 17:20 UTC, Anaphase commented on src/components/OAuth2AppTransferRecordForm.vue
> +      label="Receiving Ethereum or Email Address"
I'm just going to leave the oauth2 test page as is since it works alright and isn't really user-facing.

2018-10-31 17:22 UTC, Anaphase commented on src/views/LoginView.vue
> +            @TODO: add a "claim with a different email?" link here when that
I removed the `@TODO`,  but I wanted to keep the comment there for future implementation

2018-10-31 17:23 UTC, Anaphase commented on src/views/LoginView.vue
> +          // @TODO: should anything else happen here?
I tired to show a generic message but it didn't really make sense, because if that request fails it _probably_ means the token is invalid and a message shouldn't be showed. I just log the error and ignore it.

2018-10-31 17:25 UTC, Anaphase commented
Alright, I'm considering this PR done. It should be merged before #43 so that the query param refactoring can be applied to the new pendingUserCode in this PR.

2018-10-31 18:39 UTC, johnhforrest approved these changes

2018-10-31 18:39 UTC, merged