[Part 2 of 2] Clean up our authentication logic
codex-protocol/deprecated.web.codex-viewer pull request #43
Opened 2018-10-30 22:12 UTC by johnhforrest

There's a lot here, so bear with me.

- Fixes an issue where Vue would re-use provenance data when transitioning between record detail pages (this is the `:key` change in App.vue). It turns out the ConfirmEmail view was relying on this dirty state so I had to plumb the `confirmEmailAddress` in `vuex` as well.
- Removes a lot of redundant EventBus calls that were logging component creations. These are obsolete now that we don't use Mixpanel. Additionally, VueAnalytics is *supposed* to handle this for us.
- Created a new `vuex` module called `app` and moved some state from `auth` there and migrated the `verified-users` module there too. I'm considering combining the web3/auth ones since there's a lot of crossover but everything works as is in the current state.
- The rest of the changes are strictly around authentication logic. Most of them are a no-op and just clean up the view code a bit by moving all of the business logic to `vuex`. I also added the new `window.ethereum` code as per to address the breaking changes as per https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8. Unfortunately their daily build today is busted so I can't test out the new prompt yet (but it is backwards compatible so safe to ship for now).

Since it's a lot of code, my biggest ask for you is to review the promise chains to make sure they are returning/resolving/rejecting when they should be and I'm not doing something silly there.

I'll keep testing a few different states locally to make sure all of the edge cases we tried before are still working as expected.

2018-10-30 23:26 UTC, Anaphase requested changes

2018-10-30 23:26 UTC, Anaphase commented on src/App.vue
> +    this.$store.dispatch('app/FETCH_VERIFIED_USERS_ADDRESS_NAME_MAP')
I struggled on what to name this originally, `FETCH_VERIFIED_USERS` or `FETCH_ADDRESS_NAME_MAP`. I settled on the latter since the API route doesn't return full user objects, but feel free to rename this action to `FETCH_VERIFIED_USERS` if you like that better than the quite-verbose `FETCH_VERIFIED_USERS_ADDRESS_NAME_MAP`

2018-10-30 23:26 UTC, Anaphase commented on src/components/core/AppSideBar.vue
> +        text: 'Login',
Hah, I figured this was an actual bug and not a copy / paste error. Oops!

2018-10-30 23:26 UTC, Anaphase commented on src/store/modules/auth/actions.js
> +        return dispatch('HANDLE_LOGIN_ERROR', error)
Typically you don't want to return a promise (or any value really) from a `.catch()` (because of how the resulting value can get passed into a subsequent `.then()`). In this instance I don't think it will cause a problem, but I'd probably go ahead and remove it since it gives you no benefits either.

2018-10-30 23:26 UTC, Anaphase commented on src/store/modules/app/state.js
> +    confirmEmailAddress: null,
Can you rename this variable? When I see it I think it's supposed to be a function or something _(insert typescript joke here.)_ Maybe something like `confirmationEmailAddress` or `emailAddressToConfirm`?

2018-10-30 23:26 UTC, Anaphase commented on src/store/modules/auth/actions.js
> +        return dispatch('HANDLE_LOGIN_ERROR', error)
After seeing `HANDLE_LOGIN_ERROR` below, I'm pretty sure you can remove the returns here. If it were me, I'd also move the `throw` inside `HANDLE_LOGIN_ERROR` up into this catch as well, but the way you have it should work as well.

```
.catch((error) => {
  dispatch('HANDLE_LOGIN_ERROR', error)
  throw error
})
```

(I just like it to be clear inside a catch that you want to bubble the error up the chain.)

2018-10-30 23:28 UTC, Anaphase commented
I think you mentioned this at some point before, but it'd be nice to eventually move all the query param grabbing logic into App.vue / vuex instead of each routing doing it for itself so that query params are grabbed and removed from the route in once single place. Moving all the values to vuex is a step in the right direction though 👍 

EDIT: crap I just realized that'll refactor will affect PR #38 when I grab `pendingUserCode`

2018-10-31 16:30 UTC, johnhforrest commented on src/App.vue
> +    this.$store.dispatch('app/FETCH_VERIFIED_USERS_ADDRESS_NAME_MAP')
I'll use FETCH_VERIFIED_USERS

2018-10-31 16:30 UTC, johnhforrest commented on src/store/modules/app/state.js
> +    confirmEmailAddress: null,
I like `emailAddressToConfirm`

2018-10-31 16:31 UTC, johnhforrest commented
> I think you mentioned this at some point before, but it'd be nice to eventually move all the query param grabbing logic into App.vue / vuex instead of each routing doing it for itself so that query params are grabbed and removed from the route in once single place. Moving all the values to vuex is a step in the right direction though 👍
> 
> EDIT: crap I just realized that'll refactor will affect PR #38 when I grab `pendingUserCode`

I can look at that when I'm fixing the auth token priority stuff, so feel free to get the `pendingUserCode` stuff in there before (or hand that off to me if you don't want to make the FE changes)

2018-10-31 21:21 UTC, Anaphase approved these changes

2018-10-31 21:21 UTC, merged