Add a new 'Contact Us' view for general contact and security disclosures
codex-protocol/deprecated.web.codex-viewer pull request #48
Opened 2018-11-07 23:18 UTC by johnhforrest

![image](https://user-images.githubusercontent.com/402949/48167364-1b4e3880-e2b1-11e8-85ef-17c280f90c3b.png)

2018-11-07 23:24 UTC, Anaphase requested changes

2018-11-07 23:24 UTC, Anaphase commented on src/views/ContactUsView.vue
> +      developersHref: `mailto:support@developers.com?subject=${encodeURIComponent('Codex Viewer Developer Support')}`,
```suggestion
      developersHref: `mailto:developers@codexprotocol.com?subject=${encodeURIComponent('Codex Viewer Developer Support')}`,
```

2018-11-07 23:27 UTC, johnhforrest commented on src/views/ContactUsView.vue
> +      developersHref: `mailto:support@developers.com?subject=${encodeURIComponent('Codex Viewer Developer Support')}`,
Too much copy paste!

2018-11-08 00:36 UTC, Anaphase approved these changes

2018-11-08 16:02 UTC, merged